# Generated by Django 5.1 on 2024-11-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_appointment_user_appointment_client'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='meeting',
        ),
    ]
