# Generated by Django 5.1 on 2024-11-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_appointment_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='appointment',
        ),
    ]
