# Generated by Django 5.1 on 2024-11-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
