# Generated by Django 5.1 on 2024-11-27 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_delete_appointment'),
        ('myadmin', '0016_alter_client_date_alter_client_middle_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myadmin.client')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
