# Generated by Django 5.1.1 on 2024-12-01 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_appointment'),
        ('myadmin', '0016_alter_client_date_alter_client_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.client'),
        ),
    ]
