# Generated by Django 5.1.4 on 2024-12-06 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0020_alter_case_fir_copy_alter_case_uploaded_at'),
        ('staff', '0004_delete_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence_files/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.case')),
            ],
            options={
                'db_table': 'evidence',
            },
        ),
    ]
