# Generated by Django 5.1.1 on 2024-11-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='contact',
            new_name='phone',
        ),
    ]
