# Generated by Django 5.1.1 on 2024-11-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_rename_contact_staff_phone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff',
            table='staff1',
        ),
    ]
