# Generated by Django 5.1.1 on 2024-11-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_alter_staff_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='image',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='staff',
        ),
    ]
