# Generated by Django 5.1.1 on 2024-11-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_remove_staff_image_alter_staff_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
