# Generated by Django 5.1.1 on 2024-11-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
