# Generated by Django 5.1.1 on 2024-11-14 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_alter_staff_date_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('fir_date', models.DateField()),
                ('fir_station', models.CharField(max_length=30)),
                ('crimetype', models.CharField(max_length=30)),
                ('status', models.CharField(default='running', max_length=30)),
                ('fir_copy', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.client')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.staff')),
            ],
            options={
                'db_table': 'case',
            },
        ),
    ]
