# Generated by Django 5.1.1 on 2024-11-15 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0010_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='fir_copy',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateField(default=datetime.date(2024, 11, 15)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date',
            field=models.DateField(default=datetime.date(2024, 11, 15)),
        ),
    ]
