# Generated by Django 5.1 on 2024-11-15 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0012_rename_title_case_case_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='staff',
            new_name='staff_id',
        ),
        migrations.AlterField(
            model_name='case',
            name='fir_copy',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateField(default=datetime.date(2024, 11, 16)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date',
            field=models.DateField(default=datetime.date(2024, 11, 16)),
        ),
    ]
