# Generated by Django 5.1 on 2024-11-15 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0013_rename_client_case_client_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='staff_id',
            new_name='staff',
        ),
    ]
