# Generated by Django 5.1.4 on 2024-12-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0016_alter_client_date_alter_client_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='fir_copy',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
