# Generated by Django 5.1.4 on 2024-12-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0017_alter_case_fir_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='fir_copy',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
