# Generated by Django 5.1.4 on 2024-12-06 07:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0018_alter_case_fir_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='case',
            name='fir_copy',
            field=models.FileField(upload_to='media/'),
        ),
    ]
