# Generated by Django 5.1.4 on 2024-12-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0019_case_uploaded_at_alter_case_fir_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='fir_copy',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='case',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
